/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ApiBlobRouteImport } from './routes/api/blob'
import { Route as HoldingsSlugRouteImport } from './routes/holdings.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobRoute = ApiBlobRouteImport.update({
  id: '/api/blob',
  path: '/api/blob',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsSlugRoute = HoldingsSlugRouteImport.update({
  id: '/holdings/$slug',
  path: '/holdings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/api/blob': typeof ApiBlobRoute
  '/holdings/$slug': typeof HoldingsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/api/blob': typeof ApiBlobRoute
  '/holdings/$slug': typeof HoldingsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/maintenance': typeof MaintenanceRoute
  '/api/blob': typeof ApiBlobRoute
  '/holdings/$slug': typeof HoldingsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/maintenance' | '/api/blob' | '/holdings/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/maintenance' | '/api/blob' | '/holdings/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/maintenance'
    | '/api/blob'
    | '/holdings/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ApiBlobRoute: typeof ApiBlobRoute
  HoldingsSlugRoute: typeof HoldingsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob': {
      id: '/api/blob'
      path: '/api/blob'
      fullPath: '/api/blob'
      preLoaderRoute: typeof ApiBlobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings/$slug': {
      id: '/holdings/$slug'
      path: '/holdings/$slug'
      fullPath: '/holdings/$slug'
      preLoaderRoute: typeof HoldingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  MaintenanceRoute: MaintenanceRoute,
  ApiBlobRoute: ApiBlobRoute,
  HoldingsSlugRoute: HoldingsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
